### ISSUE TITLE
Error when I run dev after installation

### ISSUE THREAD

**Issue by armsp** [AREA44/astro-multiverse#94]
Following is the error I get when I try to run :
```bash
❯ pnpm run dev

> astro-multiverse@23.7.1 dev /home/eli/my-photos
> astro dev

  🚀  astro  v2.7.2 started in 41ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

Error: The following dependencies are imported but could not be resolved:

  js/jquery.min.js (imported by /home/eli/my-photos/src/pages/index.astro)
  js/jquery.poptrox.min.js (imported by /home/eli/my-photos/src/pages/index.astro)
  js/browser.min.js (imported by /home/eli/my-photos/src/pages/index.astro)
  js/breakpoints.min.js (imported by /home/eli/my-photos/src/pages/index.astro)
  js/util.js (imported by /home/eli/my-photos/src/pages/index.astro)
  js/main.js (imported by /home/eli/my-photos/src/pages/index.astro)

Are they installed?
    at file:///home/eli/my-photos/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/eli/my-photos/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
```

**Comment by armsp** [comment]
Yes, its a warning indeed...don't know why it says Error. And yes the application did run at localhost
